server:
  port: 9100
service-url:
  user-service: http://localhost:8100
spring:
  cloud:
    gateway:
      routes:
        -id: path_route
        uri: ${service-url.user-service}/index #匹配后路由地址
        predicates: ## 断言，路径相匹配的进行路由
        -Path=/index
