server:
  port: 8100

spring:
  application:
    name: springcloud-eureka-client

eureka:
  instance:
    instance-id: ${spring.application.name}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8300/eureka/ #Eureka地址
