server:
  port: 9090

#spring
spring:
  application:
    name: springboot-elasticsearch
  #datasource:
  #  url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&connectTimeout=1000&socketTimeout=30000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
  #  name: root
   # password: 1qazXSW@
  #  driver-class-name: com.mysql.cj.jdbc.Driver
elasticsearch:
  address: localhost:9201
  #username: elastic
  #password: 123456
  schema: http
  connectTimeout: 5000
  socketTimeout: 5000
  connectionRequestTimeout: 5000
  maxConnectNum: 100
  maxConnectPerRoute: 100
